import { ok } from "@/lib/http";

const implemented = [
  "POST /api/auth/register",
  "POST /api/auth/login",
  "POST /api/auth/forgot-password",
  "GET /api/auth/me",
  "GET /api/users/profile",
  "PUT /api/users/profile",
  "GET /api/users/settings",
  "PUT /api/users/settings",
  "GET /api/workspaces",
  "POST /api/workspaces",
  "GET /api/documents",
  "POST /api/documents",
  "GET /api/documents/:id",
  "PUT /api/documents/:id",
  "DELETE /api/documents/:id",
  "POST /api/documents/:id/renew",
  "POST /api/location/check",
  "POST /api/ocr/scan",
  "GET /api/health",
  "GET /api/notifications",
  "PUT /api/notifications/:id/read",
  "PUT /api/notifications/read-all",
  "GET /api/workspaces/:id/activity",
  "GET /api/workspaces/:id/audit",
  "GET /api/workspaces/:id/export",
  "PATCH /api/workspaces/:id",
  "DELETE /api/workspaces/:id",
  "POST /api/workspaces/:id/leave",
  "GET /api/integrations/gmail/connect-url",
  "GET /api/integrations/gmail/callback",
  "GET /api/integrations/gmail/status",
  "DELETE /api/integrations/gmail/status",
];

const planned = [
  "POST /api/auth/oauth/google",
  "POST /api/auth/oauth/apple",
  "POST /api/auth/reset-password",
  "POST /api/auth/refresh",
  "GET /api/documents/summary",
  "GET /api/ocr/result/:jobId",
  "GET /api/documents/:id/reminders",
  "PUT /api/documents/:id/reminders",
  "DELETE /api/reminders/:id",
  "GET /api/workspaces/:id",
  "POST /api/workspaces/:id/switch",
  "GET /api/workspaces/:id/members",
  "PUT /api/workspaces/:id/members/:memberId",
  "DELETE /api/workspaces/:id/members/:memberId",
  "POST /api/workspaces/:id/invitations",
  "GET /api/workspaces/:id/invite-link",
  "POST /api/invitations/accept/:token",
  "DELETE /api/workspaces/:id/invite-link",
  "GET /api/documents/:id/assignment",
  "PUT /api/documents/:id/assignment",
  "DELETE /api/documents/:id/assignment",
  "GET /api/branches",
  "GET /api/branches/:id",
  "POST /api/branches/:id/feedback",
  "GET /api/notifications/unread-count",
  "GET /api/errors",
  "POST /api/errors/:id/retry",
  "PUT /api/errors/:id/resolve",
];

export async function GET() {
  return ok({ implemented, planned });
}
